=== MattressPadley/Open_Fixture.Lib/tests/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Fixture Schema",
  "type": "object",
  "properties": {
    "Name": {
      "type": "string"
    },
    "Manufacturer": {
      "type": "string"
    },
    "Image": {
      "type": "string",
      "format": "uri"
    },
    "Manual": {
      "type": "string",
      "format": "uri"
    },
    "Dimensions": {
      "type": "object",
      "properties": {
        "Weight": {
          "type": "number"
        },
        "Height": {
          "type": "number"
        },
        "Width": {
          "type": "number"
        },
        "Depth": {
          "type": "number"
        }
      },
      "required": ["Weight", "Height", "Width", "Depth"]
    },
    "Power": {
      "type": "object",
      "properties": {
        "AC_voltage": {
          "type": "string"
        },
        "Power_Draw": {
          "type": "number"
        },
        "DC_Port": {
          "type": "string"
        },
        "DC_voltage": {
          "type": "string"
        },
        "AC_plug": {
          "type": "string"
        },
        "USB_Port": {
          "type": "boolean"
        },
        "Internal_battery": {
          "type": "boolean"
        }
      },
      "required": [
        "AC_voltage",
        "Power_Draw",
        "AC_plug",
        "USB_Port",
        "Internal_battery"
      ]
    },
    "Optics": {
      "type": "object",
      "properties": {
        "Beam_Angle": {
          "type": "string"
        },
        "Color_Temp": {
          "type": "string"
        },
        "Source": {
          "type": "string"
        },
        "LED_Array": {
          "type": "string"
        },
        "Color": {
          "type": "boolean"
        },
        "Pixel_count": {
          "type": "number"
        },
        "Lens": {
          "type": "string"
        }
      },
      "required": [
        "Beam_Angle",
        "Color_Temp",
        "Source",
        "Color"
      ]
    },
    "Control": {
      "type": "object",
      "properties": {
        "CRMX": {
          "type": "boolean"
        },
        "RDM": {
          "type": "boolean"
        },
        "Ethernet": {
          "type": "boolean"
        },
        "5_Pin_DMX": {
          "type": "boolean"
        },
        "3_Pin_DMX": {
          "type": "boolean"
        }
      },
      "required": ["CRMX", "RDM", "Ethernet", "5_Pin_DMX", "3_Pin_DMX"]
    },
    "Physical": {
      "type": "object",
      "properties": {
        "mount": {
          "type": "string"
        },
        "IP_Rating": {
          "type": "string"
        }
      },
      "required": ["mount"]
    }
  },
  "required": [
    "Name",
    "Manufacturer",
    "Dimensions",
    "Power",
    "Optics",
    "Control",
    "Physical"
  ]
}

=== MattressPadley/Open_Fixture.Lib/Fixtures/Creamsource/Vortex8.json
{
    "Name": "Vortex8",
    "Manufacturer": "Creamsource",
    "Image": "https://creamsource.com/wp-content/uploads/2024/01/vortex8s_ip65_1080p.mp4",
    "Manual": "https://knowledge.creamsource.com",
    "Dimensions": {
        "Weight": 39.2,
        "Height": 21.7,
        "Width": 32.7,
        "Depth": 6.4
    },
    "Power": {
        "AC_voltage": "100-240V",
        "Power_Draw": 650,
        "DC_Port": "3-Pin XLR",
        "DC_voltage": "48V",
        "AC_plug": "Edison",
        "USB_Port": true,
        "Internal_battery": false
    },
    "Optics": {
        "Beam_Angle": "20\u00b0",
        "Color_Temp": "2200K-15000K",
        "Source": "LED",
        "LED_Array": "RGBW",
        "Color": true,
        "Pixel_count": 8,
        "Lens": "20\u00b0 Native, 110\u00b0 With Diffusion"
    },
    "Control": {
        "CRMX": true,
        "RDM": true,
        "Ethernet": true,
        "5_Pin_DMX": true,
        "3_Pin_DMX": false
    },
    "Physical": {
        "mount": "Junior Pin",
        "IP_Rating": "IP65"
    }
}

=== MattressPadley/Open_Fixture.Lib/Fixtures/Fiilex/Q5-Color.json
{
    "Name": "Q5 Color",
    "Manufacturer": "Fiilex",
    "Image": "https://www.fiilex.com/products/Q5_Color.php",
    "Manual": "https://www.fiilex.com/downloads/Q5_Color_Manual.pdf",
    "Dimensions": {
        "Weight": 7.3,
        "Height": 15.7,
        "Width": 11.1,
        "Depth": 7.8
    },
    "Power": {
        "AC_voltage": "100-240V AC, 50-60Hz",
        "Power_Draw": 175,
        "DC_Port": "XLR-3",
        "DC_voltage": "24-48V DC",
        "AC_plug": "powerCON TRUE1",
        "USB_Port": true,
        "Internal_battery": false
    },
    "Optics": {
        "Beam_Angle": "12\u00b0-55\u00b0 (80\u00b0 without fresnel)",
        "Color_Temp": "2000-10000K",
        "Source": "LED",
        "LED_Array": "RGBW",
        "Color": true,
        "Pixel_count": 1,
        "Lens": "5 inch Fresnel"
    },
    "Control": {
        "CRMX": false,
        "RDM": true,
        "Ethernet": false,
        "5_Pin_DMX": true,
        "3_Pin_DMX": false
    },
    "Physical": {
        "mount": "Combo (baby stud female / junior stud male)",
        "IP_Rating": "IP-X5"
    }
}

=== MattressPadley/Open_Fixture.Lib/Fixtures/Fiilex/Q3-Color.json
{
    "Name": "Q3 Color",
    "Manufacturer": "Fiilex",
    "Image": "https://www.fiilex.com/products/Q3_Color.php",
    "Manual": "https://www.fiilex.com/downloads/Q3_Color_Manual.pdf",
    "Dimensions": {
        "Weight": 4.5,
        "Height": 5.7,
        "Width": 6.8,
        "Depth": 9
    },
    "Power": {
        "AC_voltage": "100-240V AC, 50-60Hz",
        "Power_Draw": 90,
        "DC_Port": "5.5mm x 2.5mm Barrel",
        "DC_voltage": "14-30V DC",
        "AC_plug": "Standard Plug",
        "USB_Port": true,
        "Internal_battery": false
    },
    "Optics": {
        "Beam_Angle": "15\u00b0-45\u00b0 (55\u00b0 without fresnel)",
        "Color_Temp": "2000-10000K",
        "Source": "LED",
        "LED_Array": "RGBW",
        "Color": true,
        "Pixel_count": 1,
        "Lens": "5 inch Fresnel"
    },
    "Control": {
        "CRMX": true,
        "RDM": true,
        "Ethernet": false,
        "5_Pin_DMX": true,
        "3_Pin_DMX": false
    },
    "Physical": {
        "mount": "5/8\" receiver",
        "IP_Rating": "IP-X5"
    }
}

=== MattressPadley/Open_Fixture.Lib/Fixtures/Fiilex/Q10-Color.json
{
    "Name": "Q10 Color",
    "Manufacturer": "Fiilex",
    "Image": "https://www.fiilex.com/products/Q10_Color.php",
    "Manual": "https://www.fiilex.com/downloads/Q10_Color_Manual.pdf",
    "Dimensions": {
        "Weight": 44,
        "Height": 19.8,
        "Width": 18.1,
        "Depth": 10.8
    },
    "Power": {
        "AC_voltage": "100-240V AC, 50-60Hz",
        "Power_Draw": 900,
        "DC_Port": "powerCON 32A",
        "DC_voltage": "48V DC",
        "AC_plug": "powerCON TRUE1",
        "USB_Port": true,
        "Internal_battery": false
    },
    "Optics": {
        "Beam_Angle": "11\u00b0-65\u00b0 (78\u00b0 without Fresnel)",
        "Color_Temp": "2000-10000K",
        "Source": "LED",
        "LED_Array": "RGBW",
        "Color": true,
        "Pixel_count": 1,
        "Lens": "10 inch Fresnel"
    },
    "Control": {
        "CRMX": true,
        "RDM": true,
        "Ethernet": true,
        "5_Pin_DMX": true,
        "3_Pin_DMX": false
    },
    "Physical": {
        "mount": "Combo (baby stud female / junior stud male)",
        "IP_Rating": "IP-X5"
    }
}

=== MattressPadley/Open_Fixture.Lib/Fixtures/ARRI/Orbiter.json
{
    "Name": "Orbiter",
    "Manufacturer": "ARRI",
    "Image": "https://www.arri.com/resource/image/1169042/portrait_ratio1x1/300/300/6bc7524be40a2a11d59f1227f8584d9a/dY/orbiter-introduction-main-05.png",
    "Manual": "https://www.arri.com/resource/blob/169364/ca6d0cbd6cfe05c25f72f49b0f3fc65e/orbiter-operating-manual-en-data.pdf",
    "Dimensions": {
        "Weight": 25.8,
        "Height": 15.6,
        "Width": 14.8,
        "Depth": 9.6
    },
    "Power": {
        "AC_voltage": "100-240V",
        "Power_Draw": 400,
        "DC_Port": "3-pin XLR",
        "DC_voltage": "48V",
        "AC_plug": "PowerCon TRUE1",
        "USB_Port": true,
        "Internal_battery": false
    },
    "Optics": {
        "Beam_Angle": "80\u00b0",
        "Color_Temp": "2000K - 20000K",
        "Source": "LED",
        "LED_Array": "RGBACL",
        "Color": true,
        "Pixel_count": 1,
        "Lens": "Various lenses available"
    },
    "Control": {
        "CRMX": true,
        "RDM": true,
        "Ethernet": true,
        "5_Pin_DMX": true,
        "3_Pin_DMX": false
    },
    "Physical": {
        "mount": "Junior Pin",
        "IP_Rating": "IP20"
    }
}

=== MattressPadley/Open_Fixture.Lib/Fixtures/Mole-Richardson/1,000-Watt-Molequartz-Baby-Baby-Solarspot.json
{
    "Name": "1,000 Watt Molequartz Baby-Baby Solarspot",
    "Manufacturer": "Mole-Richardson",
    "Image": "https://www.mole.com/images/2831_new_large.jpg",
    "Dimensions": {
        "Weight": 9.5,
        "Height": 9.25,
        "Width": 7.375,
        "Depth": 8.875
    },
    "Power": {
        "AC_voltage": "120/240",
        "Power_Draw": 1000,
        "DC_voltage": "120/240",
        "AC_plug": "Edison",
        "USB_Port": false,
        "Internal_battery": false
    },
    "Optics": {
        "Beam_Angle": "21\u00b0 to 70\u00b0",
        "Source": "Quartz",
        "Color_Temp": "3200k",
        "Lens": "4 15/32 inch Fresnel",
        "Color": false
    },
    "Control": {
        "CRMX": false,
        "RDM": false,
        "Ethernet": false,
        "5_Pin_DMX": false,
        "3_Pin_DMX": false
    },
    "Physical": {
        "mount": "Baby Pin",
        "IP_Rating": "None"
    }
}
